
package com.yuhaowin.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWordWSService", targetNamespace = "http://service.webservice.yuhaowin.com/", wsdlLocation = "http://localhost:8989/HelloWorld?wsdl")
public class HelloWordWSService
    extends Service
{

    private final static URL HELLOWORDWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWORDWSSERVICE_EXCEPTION;
    private final static QName HELLOWORDWSSERVICE_QNAME = new QName("http://service.webservice.yuhaowin.com/", "HelloWordWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8989/HelloWorld?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWORDWSSERVICE_WSDL_LOCATION = url;
        HELLOWORDWSSERVICE_EXCEPTION = e;
    }

    public HelloWordWSService() {
        super(__getWsdlLocation(), HELLOWORDWSSERVICE_QNAME);
    }

    public HelloWordWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWORDWSSERVICE_QNAME, features);
    }

    public HelloWordWSService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWORDWSSERVICE_QNAME);
    }

    public HelloWordWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWORDWSSERVICE_QNAME, features);
    }

    public HelloWordWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWordWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWordWS
     */
    @WebEndpoint(name = "HelloWordWSPort")
    public HelloWordWS getHelloWordWSPort() {
        return super.getPort(new QName("http://service.webservice.yuhaowin.com/", "HelloWordWSPort"), HelloWordWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWordWS
     */
    @WebEndpoint(name = "HelloWordWSPort")
    public HelloWordWS getHelloWordWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webservice.yuhaowin.com/", "HelloWordWSPort"), HelloWordWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORDWSSERVICE_EXCEPTION!= null) {
            throw HELLOWORDWSSERVICE_EXCEPTION;
        }
        return HELLOWORDWSSERVICE_WSDL_LOCATION;
    }

}
