
package com.yuhaowin.webservice.messagetemplate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWeChatPushServicePortType", targetNamespace = "http://facade.utc.js189.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWeChatPushServicePortType {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://facade.utc.js189.cn/")
    @RequestWrapper(localName = "weChatMsgPush", targetNamespace = "http://facade.utc.js189.cn/", className = "com.yuhaowin.webservice.messagetemplate.WeChatMsgPush")
    @ResponseWrapper(localName = "weChatMsgPushResponse", targetNamespace = "http://facade.utc.js189.cn/", className = "com.yuhaowin.webservice.messagetemplate.WeChatMsgPushResponse")
    public String weChatMsgPush(
        @WebParam(name = "arg0", targetNamespace = "http://facade.utc.js189.cn/")
        String arg0);

}
